solver:
  mode: qss_dcr
io:
  output_dir: output/test_run_Tx_profile/exclude_mi
  atomic_data_root: atomic_data/
  data_tables_root: data_tables/
  verbose_logging: true
species:
- name: H_Atom
  filename: sclit.01
  is_molecule: false
- name: H2_Molecule
  filename: sclit_M.01
  is_molecule: true
grid:
  length_cm: 2.0
  num_cells: 100
  type: log
  first_cell_cm: 0.001
  poloidal_width_cm: 100.0
plasma:
  total_density_cm3: 1e15
  Te_eV: 5.0
  Ti_eV: 5.0
  electron_temperature_profile:
    enabled: true
    type: linear_x
    x_start_cm: 0.0
    x_end_cm: 2.0
    value_start_eV: 0.5
    value_end_eV: 5.0
  ion_temperature_profile:
    enabled: true
    type: linear_x
    x_start_cm: 0.0
    x_end_cm: 2.0
    value_start_eV: 0.5
    value_end_eV: 5.0
  neutral_atom_temperature_eV: 0.1
  neutral_molecule_temperature_eV: 0.1
  initial_conditions:
  - index: 0
    fraction: 0.1
  - index: 1
    fraction: 0.88
  - index: 31
    fraction: 0.01
wall:
  material: W
  sheath_potential_drop: 4.0
  temperature_eV: 0.1
numerics:
  tolerance: 1.0e-7
  max_iterations: 500
  relaxation: 0.2
  marching_slow_iter_threshold: 100
  marching_guess_retries: 3
  qss_exclude_molecular_ion_from_transient_reconstruction: true
