# CMake generated Testfile for 
# Source directory: /Users/asimida/Desktop/DCR_code
# Build directory: /Users/asimida/Desktop/DCR_code/build_omp_on
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(StructureCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_structure")
set_tests_properties(StructureCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;205;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(PhysicsCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_physics")
set_tests_properties(PhysicsCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;213;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(StateCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_state")
set_tests_properties(StateCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;219;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(IOCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_io")
set_tests_properties(IOCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;225;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(TemperatureProfileCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_temperature_profile")
set_tests_properties(TemperatureProfileCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;231;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(EEDFGeneralizedPowerCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_eedf_generalized_power")
set_tests_properties(EEDFGeneralizedPowerCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;237;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(AtomicReaderCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_atomic_reader")
set_tests_properties(AtomicReaderCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;247;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(AtomicDataCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_atomic_data")
set_tests_properties(AtomicDataCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;254;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(AtomicProcessCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_atomic_process")
set_tests_properties(AtomicProcessCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;260;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(MolecularProcessCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_molecular_process")
set_tests_properties(MolecularProcessCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;266;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(RateMatrixCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_rate_matrix")
set_tests_properties(RateMatrixCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;273;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(RateAnalysisCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_rate_analysis")
set_tests_properties(RateAnalysisCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;280;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(MCXIntegrationCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_mcx_integration")
set_tests_properties(MCXIntegrationCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;287;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(BoundaryPhaseCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_boundary_phase")
set_tests_properties(BoundaryPhaseCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;294;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(EEDFBoundaryRegressionCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_eedf_boundary_regression")
set_tests_properties(EEDFBoundaryRegressionCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;301;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(MarchingImplicitCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_marching_implicit")
set_tests_properties(MarchingImplicitCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;349;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(MarchingDriverCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_marching_driver")
set_tests_properties(MarchingDriverCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;356;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(HDF5OutputCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_hdf5_output")
set_tests_properties(HDF5OutputCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;364;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(RegressionReferenceCheck "/Users/asimida/Desktop/DCR_code/build_omp_on/bin/check_regression_reference")
set_tests_properties(RegressionReferenceCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;371;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(PostprocessSmokeCheck "/opt/anaconda3/bin/python3.12" "/Users/asimida/Desktop/DCR_code/tests/test_postprocess_smoke.py")
set_tests_properties(PostprocessSmokeCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;383;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(PostprocessLabelCheck "/opt/anaconda3/bin/python3.12" "/Users/asimida/Desktop/DCR_code/tests/test_postprocess_labels.py")
set_tests_properties(PostprocessLabelCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;389;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(DissociationChannelParserCheck "/opt/anaconda3/bin/python3.12" "/Users/asimida/Desktop/DCR_code/tests/test_dissociation_channel_parser.py")
set_tests_properties(DissociationChannelParserCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;395;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(DissociationChannelSmokeCheck "/opt/anaconda3/bin/python3.12" "/Users/asimida/Desktop/DCR_code/tests/test_dissociation_channel_smoke.py")
set_tests_properties(DissociationChannelSmokeCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;401;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(DissociationChannelValidationCheck "/opt/anaconda3/bin/python3.12" "/Users/asimida/Desktop/DCR_code/tests/test_dissociation_channel_validation.py")
set_tests_properties(DissociationChannelValidationCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;407;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(DissociationChannelSummaryTableCheck "/opt/anaconda3/bin/python3.12" "/Users/asimida/Desktop/DCR_code/tests/test_dissociation_channel_summary_table.py")
set_tests_properties(DissociationChannelSummaryTableCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;413;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(DissociationChannelNonadiabaticCheck "/opt/anaconda3/bin/python3.12" "/Users/asimida/Desktop/DCR_code/tests/test_dissociation_channel_nonadiabatic.py")
set_tests_properties(DissociationChannelNonadiabaticCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;419;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(OCRReferenceTableCheck "/opt/anaconda3/bin/python3.12" "/Users/asimida/Desktop/DCR_code/tests/test_ocr_reference_table.py")
set_tests_properties(OCRReferenceTableCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;425;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
subdirs("_deps/yaml-cpp-build")
