# CMake generated Testfile for 
# Source directory: /Users/asimida/Desktop/DCR_code
# Build directory: /Users/asimida/Desktop/DCR_code/build-debug
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(StructureCheck "/Users/asimida/Desktop/DCR_code/build-debug/bin/check_structure")
set_tests_properties(StructureCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;130;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(PhysicsCheck "/Users/asimida/Desktop/DCR_code/build-debug/bin/check_physics")
set_tests_properties(PhysicsCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;138;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(StateCheck "/Users/asimida/Desktop/DCR_code/build-debug/bin/check_state")
set_tests_properties(StateCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;144;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(IOCheck "/Users/asimida/Desktop/DCR_code/build-debug/bin/check_io")
set_tests_properties(IOCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;150;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(AtomicReaderCheck "/Users/asimida/Desktop/DCR_code/build-debug/bin/check_atomic_reader")
set_tests_properties(AtomicReaderCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;160;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(AtomicDataCheck "/Users/asimida/Desktop/DCR_code/build-debug/bin/check_atomic_data")
set_tests_properties(AtomicDataCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;167;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(AtomicProcessCheck "/Users/asimida/Desktop/DCR_code/build-debug/bin/check_atomic_process")
set_tests_properties(AtomicProcessCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;173;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(MolecularProcessCheck "/Users/asimida/Desktop/DCR_code/build-debug/bin/check_molecular_process")
set_tests_properties(MolecularProcessCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;179;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(RateMatrixCheck "/Users/asimida/Desktop/DCR_code/build-debug/bin/check_rate_matrix")
set_tests_properties(RateMatrixCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;186;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(MCXIntegrationCheck "/Users/asimida/Desktop/DCR_code/build-debug/bin/check_mcx_integration")
set_tests_properties(MCXIntegrationCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;193;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(BoundaryPhaseCheck "/Users/asimida/Desktop/DCR_code/build-debug/bin/check_boundary_phase")
set_tests_properties(BoundaryPhaseCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;200;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(MarchingImplicitCheck "/Users/asimida/Desktop/DCR_code/build-debug/bin/check_marching_implicit")
set_tests_properties(MarchingImplicitCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;207;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(MarchingDriverCheck "/Users/asimida/Desktop/DCR_code/build-debug/bin/check_marching_driver")
set_tests_properties(MarchingDriverCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;214;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(HDF5OutputCheck "/Users/asimida/Desktop/DCR_code/build-debug/bin/check_hdf5_output")
set_tests_properties(HDF5OutputCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;222;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(RegressionReferenceCheck "/Users/asimida/Desktop/DCR_code/build-debug/bin/check_regression_reference")
set_tests_properties(RegressionReferenceCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;229;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(PostprocessSmokeCheck "/opt/anaconda3/bin/python3.12" "/Users/asimida/Desktop/DCR_code/tests/test_postprocess_smoke.py")
set_tests_properties(PostprocessSmokeCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;235;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
add_test(PostprocessLabelCheck "/opt/anaconda3/bin/python3.12" "/Users/asimida/Desktop/DCR_code/tests/test_postprocess_labels.py")
set_tests_properties(PostprocessLabelCheck PROPERTIES  _BACKTRACE_TRIPLES "/Users/asimida/Desktop/DCR_code/CMakeLists.txt;241;add_test;/Users/asimida/Desktop/DCR_code/CMakeLists.txt;0;")
subdirs("_deps/yaml-cpp-build")
